In [33]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [34]:
ds = pd.read_csv("/content/sample_data/Customer_Behaviour.csv")

In [35]:
ds.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [36]:
ds = pd.get_dummies(ds, columns=["Gender"])

In [37]:
ds.head()

    User ID  Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0  15624510   19            19000          0          False         True
1  15810944   35            20000          0          False         True
2  15668575   26            43000          0           True        False
3  15603246   27            57000          0           True        False
4  15804002   19            76000          0          False         True

In [38]:
X = ds.iloc[:, [0,1,2,4,5]]
y = ds.iloc[:, [3]]

In [39]:
X

      User ID  Age  EstimatedSalary  Gender_Female  Gender_Male
0    15624510   19            19000          False         True
1    15810944   35            20000          False         True
2    15668575   26            43000           True        False
3    15603246   27            57000           True        False
4    15804002   19            76000          False         True
..        ...  ...              ...            ...          ...
395  15691863   46            41000           True        False
396  15706071   51            23000          False         True
397  15654296   50            20000           True        False
398  15755018   36            33000          False         True
399  15594041   49            36000           True        False

[400 rows x 5 columns]

In [40]:
y

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [41]:
X_Train, X_Test, y_Train, y_Test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [42]:
y_pred = classifier.predict(X_Test)

In [43]:
cm = confusion_matrix(y_Test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[56  2]
 [13  9]]

In [44]:
accuracy = accuracy_score(y_Test, y_pred)
precision = precision_score(y_Test, y_pred)
recall = recall_score(y_Test, y_pred)
f1 = f1_score(y_Test, y_pred)

In [45]:
print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-score: {f1:.2f}")

Accuracy: 0.81
Precision: 0.82
Recall: 0.41
F1-score: 0.55